version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment: 
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/:/var/lib/postgresql/data